### ISSUE TITLE
sdk-core-nodejs Create overload OAuth method to accept custom function to obtain p12 key

### ISSUE THREAD

**Issue by kktam** [Mastercard/sdk-core-nodejs#3]
The current constructor method for [OAuth](https://github.com/Mastercard/sdk-core-nodejs/blob/master/lib/security/oauth/oauth.js) uses fs to read local disk drive to obtain contents of the p12 key.

While this works well in host servers, this becomes a big limitation to support a variety of new cloud deployment models, such as AWS lambda, where the Mastercard API workflow can be executed inside a Lambda function, and it does not have access to any physical disks. 

In this scenario, the OAuth API will need to obtain the P12 key from either streams, S3 objects, DynamoDB, or API to other cloud stores.

Similar needs will be if the Mastercard API is deployed to Microsoft Azure functions or Google Cloud Functions as well.

While it is very generous of MasterCard if the API team can actually provide all the integrating code to pick up the P12 keys from all the new cloud sources, it may be just adequate to provide a custom function hook, and other developers can come up with the code to integrate to new and emerging cloud technologies.

the exact code in question is here:

[oauth.js](https://github.com/Mastercard/sdk-core-nodejs/blob/master/lib/security/oauth/oauth.js)

```
function OAuth(consumerKey, p12Path, alias, password) {
    if(!utils.isSet(consumerKey)) {
        throw new error.SDKError('Consumer key is not set');
    }

    if(!utils.isSet(p12Path)) {
        throw new error.SDKError('Path to .p12 file is not set');
    }

    if(!utils.isSet(alias)) {
        throw new error.SDKError('Key alias is not set');
    }

    if(!utils.isSet(password)) {
        throw new error.SDKError('Keystore password is not set');
    }

    this.consumerKey = consumerKey;
    this.privateKey = _getPrivateKey(p12Path, alias, password);
...

var _getPrivateKey = function (p12Path, alias, password) {
    // 1) Read p12 file
    var p12File = fs.readFileSync(p12Path, 'binary');     <= this reads from the local disk
```

**Comment by ade90036** [comment]
I perfextly agree with this. We have enabled other languages with similar
features (inputstream  java/csharp) but never had the need for nodejs.

If you feel confortable in coding a solution which would work for one of
those scenario or your particular scenario and make it available as a pull
request, ill be happy to review it and take it.😊

Regards

Ade

On 12 Sep 2017 07:33, "Ka Tam" <notifications@github.com> wrote:

The current constructor method for OAuth
<https://github.com/Mastercard/sdk-core-nodejs/blob/master/lib/security/oauth/oauth.js>
uses fs to read local disk drive to obtain contents of the p12 key.

While this works well in host servers, this becomes a big limitation to
support a variety of new cloud deployment models, such as AWS lambda, where
the Mastercard API workflow can be executed inside a Lambda function, and
it does not have access to any physical disks.

In this scenario, the OAuth API will need to obtain the P12 key from either
streams, S3 objects, DynamoDB, or API to other cloud stores.

Similar needs will be if the Mastercard API is deployed to Microsoft Azure
functions or Google Cloud Functions as well.

While it is very generous of MasterCard if the API team can actually
provide all the integrating code to pick up the P12 keys from all the new
cloud sources, it may be just adequate to provide a custom function hook,
and other developers can come up with the code to integrate to new and
emerging cloud technologies.

the exact code in question is here:

oauth.js
<https://github.com/Mastercard/sdk-core-nodejs/blob/master/lib/security/oauth/oauth.js>

function OAuth(consumerKey, p12Path, alias, password) {
    if(!utils.isSet(consumerKey)) {
        throw new error.SDKError('Consumer key is not set');
    }

    if(!utils.isSet(p12Path)) {
        throw new error.SDKError('Path to .p12 file is not set');
    }

    if(!utils.isSet(alias)) {
        throw new error.SDKError('Key alias is not set');
    }

    if(!utils.isSet(password)) {
        throw new error.SDKError('Keystore password is not set');
    }

    this.consumerKey = consumerKey;
    this.privateKey = _getPrivateKey(p12Path, alias, password);
...

var _getPrivateKey = function (p12Path, alias, password) {
    // 1) Read p12 file
    var p12File = fs.readFileSync(p12Path, 'binary');     <= this
reads from the local disk

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Mastercard/sdk-core-nodejs/issues/3>, or mute the thread

**Comment by kktam** [comment]
@ade90036  Do you have any coding guidelines regarding MasterCard API?

In this case, since the original OAuth() is already in production. Do you prefer overloading

```
from 
function OAuth(consumerKey, p12Path, alias, password) 

to
function OAuth(consumerKey, p12Path, alias, password) 

and internally the function will detect whether p12PathOrFunc is a path string, or a function
```

This will create a constructor that looks more like the original, or

```
function OAuth(consumerKey, p12Path, alias, password) 
function OAuthWithKeyFunc(consumerKey, p12Func, alias, password) 
```

from the looks of the code, this style may require to repeat a lot of code in constructors twice.

**Comment by kktam** [comment]
After some thought I prefer the first method and try that first.

**Comment by ade90036** [comment]
@kktam, i'm not sure i follow why the synchronous is a problem. Keep in mind that this function is only called in the SDK initialisation block and hence is was not intended to be called in an asynchronously manner (constructor).

I think the best way is to add an optional parameter to the constructor signature.

```
function OAuth(consumerKey, p12Path, alias, password, getPrivateKeyFunc = 0) {
 ```

the ***getPrivateKeyFunc*** can be a function which is passed in and used to pkcs12 from, stream, bytestream, base64, or whatever the user / system requires.

Thoughts?

**Comment by kktam** [comment]
@ade90036 I had my first test version at [my test branch](https://github.com/kktam/sdk-core-nodejs/tree/oauth-test1).  The problem with this version is the I am trying to keep the signature of the constructor and return the OAuth header string.  However in the Cloud scenario (S3), the S3 library may not be synchronous (the library s3fs I am testing now, is async). This create a situation where the signing will occur before the p12 key contents have actually returned. I have not yet found a way to pause the originating function OAuth() call and hold off running _signRequest, even with a Promise. 

Please take a look at my branch, and comment to see how I can improve the first version. I have built a test case [lostStolenAwsS3.js](https://github.com/kktam/sdk-core-nodejs/blob/oauth-test1/test/lostStolenAwsS3.js), so you can test the change I made.

**Comment by kktam** [comment]
@ade90036 I have a working version in my [oauth-test-1 branch](https://github.com/kktam/sdk-core-nodejs/tree/oauth-test1) now. The exact commit that was working is [this one](https://github.com/kktam/sdk-core-nodejs/commit/cbfd0918d766a393e835ab45dce173f4a49d5df2).  

This example illustrate the difficulty to get the application client to understand the private key is not always available when the authentication object is originally created. This fix currently requires a hard-wait for some time. This cannot be fixed by Promise (At the very minimum using a Promise inside the mocha beforeEach() function is not going to slow mocha to wait for the key before it executes the rest of the function.

It is not the prettiest solution, but at this point it works. Any suggestions on improvement is welcome. If this looks ok, I will issue a pull request.

**Comment by kktam** [comment]
@ade90036 I have further enhanced the library to made it support multi-threaded operations again. 
The commit is in (this version)[https://github.com/kktam/sdk-core-nodejs/commit/f629cdd08b77557dcf7718408a5e137e515a803f]. This now fully supports and Promise checking for the completion of P12 file download from Cloud sources, and allows this fetch the whole authentication string, without exposing too much internal details to the caller.

the version will require the user to provide a cloud based p12 function with a specific format (the template is demonstrated in mocha tests). Please look at the mocha test for more details.

I shall provide updates to readme next.

**Comment by kktam** [comment]
@ade90036 upon accepting the solution, I would request MasterCard API team to open up free account with Amazon AWS, and create a simple S3 bucket, to host the [p12 demo key](mcapi_sandbox_key.p12). This will free up the S3 bucket I am currently using in my forked branch to demo to your team, and I will also replace the link in the mocha tests to the S3 bucket you provided.

**Comment by kktam** [comment]
This issue has been completed as enhancement, under [Pull Request 7](https://github.com/Mastercard/sdk-core-nodejs/pull/7). 

For details on how to use this feature, please take a look at [test case lostStolenAwsS3.js](https://github.com/Mastercard/sdk-core-nodejs/blob/master/test/lostStolenAwsS3.js) for details.
